version: '3.8'
services:
  # postgis instance
  postgis:
    image: postgis/postgis
    container_name: postgis
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
  # pgAdmin instance
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
