version: '3.8'

volumes:
  pg_data: {}

services:
  # postgis instance
  postgis:
    image: postgis/postgis:14-3.2-alpine #postgis/postgis
    container_name: postgis
    environment:
      - POSTGRES_DB=${PG_DATABASE:-postgres}
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-password}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./foret_protectrice.sql:/docker-entrypoint-initdb.d/foret_protectrice.sql
    ports:
      - '${PG_PORT:-5433}:5432'
    restart: unless-stopped
  # pgAdmin instance
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${EMAIL:-joe@acme.org}
      - PGADMIN_DEFAULT_PASSWORD=${PASSWORD:-password}
    depends_on:
      - postgis
    ports:
      - '5050:80'
    restart: unless-stopped

